version: '3.8'
services:
  frontend:
    build: ./FE-Angular
    ports:
      - "4200:4200"
    networks:
      - app-network
    volumes:
      - ./FE-Angular:/app
      - /app/node_modules

networks:
  app-network: