services:
  frontend:
    build: ./FE-Angular
    ports:
      - "4201:4200" # ホスト側のポートを4201に変更
    networks:
      - app-network
    volumes:
      - ./FE-Angular:/app
      - /app/node_modules

networks:
  app-network: